import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Hero from "@/section/hero";
import AOS from "aos";
import "aos/dist/aos.css";

import {
  FaApple,
  FaComments,
  FaGooglePlay,
  FaHeart,
  FaPlay,
  FaRegListAlt,
  FaUsers,
} from "react-icons/fa";
import { BiGroup } from "react-icons/bi";
import { useEffect } from "react";
import About from "../section/about";
import Achievement from "../section/Achievement";
import Features from "../section/Features";
import CTA from "../section/CTA";
import Header from "@/component/layout/Header";
import Footer from "@/component/layout/Footer";
import Layout from "@/component/layout/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    AOS.init();
    AOS.refresh();
  }, []);
  return (
    <>
      <Layout>
        <Head>
          <title>Netbook</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="">
          <Hero />

          <About />

          <Achievement />

          <Features />

          <CTA />
        </main>
      </Layout>
    </>
  );
}
