import AOS from "aos";
import "aos/dist/aos.css";

import React, { useState, useEffect } from "react";
import axios from "axios";

import Layout from "@/component/layout/layout";
import Head from "next/head";
import Image from "next/image";

type DataType = {
  id: number;
  first_name: string;
  email: string;
  avatar: string;
};

export default function App() {
  const [users, setUsers] = useState<DataType[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      AOS.init();
      try {
        const response = await axios.get("https://reqres.in/api/users/");
        setUsers(response.data.data);
      } catch (error) {
        console.log(error);
      }
    };
    fetchData();
  }, []);

  return (
    <>
      <Layout>
        <Head>
          <title>Netbook</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="overflow-hidden bg-[#F1F6FD]">
          <div className="flex flex-col items-center py-10 max-w-6xl mx-auto">
            <h1 className="text-[#0A093D] font-bold text-4xl pb-5">
              Netbook Member
            </h1>
            <ul className="flex flex-wrap justify-center">
              {users.length &&
                users.map((user) => (
                  <li key={user.id}>
                    <div
                      className="flex flex-col items-center p-2 bg-white m-2 w-[256px] h-[250px] scale-95 transition duration-500 hover:scale-105 rounded-lg shadow-md"
                      data-aos="zoom-in"
                    >
                      <Image
                        src={user.avatar}
                        alt="Picture of the author"
                        height={200}
                        width={200}
                      />
                      <div className="flex flex-col items-start justify-start w-full pl-5">
                        <p className="text-[#217BF4] font-semibold">
                          {user.first_name}
                        </p>
                        <p className="text-[#217BF4] font-regular">
                          {user.email}
                        </p>
                      </div>
                    </div>
                  </li>
                ))}
            </ul>
          </div>
        </main>
      </Layout>
    </>
  );
}
